[sdl]
fullscreen = false
windowresolution = original
output = openglnb

[render]
aspect = false
scaler = none
glshader = san3_crop2.glsl

[cpu]
cputype = 386_prefetch
core = auto

[dosbox]
machine = svga_s3
memsize = 16

[autoexec]
mount c "C:\Users\admin\Downloads\dos\san3"
c:
play.bat
exit
